- name: Instalando o apache - Debian
  apt: name=apache2 state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Iniciando o apache - Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
